
services:
  apache:
    build: ./apache
    container_name: teevity-apache
    volumes:
      - ${TEE_OPT_BASEPATH}/apache/webdav:/usr/local/apache2/htdocs/webdav:rw
      - ${TEE_OPT_BASEPATH}/apache/logs:/usr/local/apache2/logs:rw
      - ${TEE_OPT_BASEPATH}/apache/auth:/usr/local/apache2/auth:rw
      - ${TEE_OPT_BASEPATH}/apache/davlocks:/usr/local/apache2/davlocks:rw
    networks:
      - teevity-net
    ports:
      - "6080:80"

  nginx:
    build: ./nginx
    container_name: teevity-nginx
    depends_on:
      - apache
    volumes:
      - ${TEE_OPT_BASEPATH}/nginx/logs:/var/log/nginx
      - ${TEE_OPT_BASEPATH}/certs/live/teevity.com:/etc/letsencrypt
    ports:
      - "${TEE_WEBDAV_HTTP_PORT:-7080}:80"
      - "${TEE_WEBDAV_HTTPS_PORT:-7443}:443"
    networks:
      - teevity-net
    expose:
      - "443"
      - "80"

  mitmproxy:
    image: mitmproxy/mitmproxy:latest
    container_name: teevity-mitmproxy
    depends_on:
      - apache
    entrypoint: ["/opt/teevity/combine-privkey-and-cert-entrypoint.sh"]
    command: >
      mitmweb
      --mode reverse:http://teevity-apache:80
      --listen-host 0.0.0.0
      --listen-port 443
      --web-host 0.0.0.0
      --web-port 8081
      --set web_password='notARealSecret'
      --set block_global=false
      --certs *.teevity.com=/opt/teevity/certs/combined-key-cert.pem
    networks:
      - teevity-net
    ports:
      - "8443:443"   # HTTPS traffic intercepted
      - "8081:8081"  # Web UI for inspection
    volumes:
      - ${TEE_OPT_BASEPATH}/mitmproxy:/home/mitmproxy                   # logs, saved flows, certs
      - ${TEE_OPT_BASEPATH}/certs/live/teevity.com/:/opt/teevity/certs  # certifcates file directory
      - ./mitmweb/scripts/combine-privkey-and-cert-entrypoint.sh:/opt/teevity/combine-privkey-and-cert-entrypoint.sh:ro

networks:
  teevity-net:
    driver: bridge
