
services:
  apache:
    build: ./apache
    container_name: teevity-apache
    volumes:
      - /opt/teevity/apache/webdav:/usr/local/apache2/htdocs/webdav:rw
      - /opt/teevity/apache/logs:/usr/local/apache2/logs:rw
    networks:
      - teevity-net

  nginx:
    build: ./nginx
    container_name: teevity-nginx
    depends_on:
      - apache
    volumes:
      - /opt/teevity/nginx/logs:/var/log/nginx
      - /opt/teevity/certs:/etc/letsencrypt
    ports:
      - "${TEE_WEBDAV_HTTP_PORT:-7580}:80"
      - "${TEE_WEBDAV_HTTPS_PORT:-7543}:443"
    networks:
      - teevity-net

networks:
  teevity-net:
    driver: bridge
